[project]
name = "stacks-lending"
authors = []
description = ""
telemetry = false
requirements = []
cache_dir = ".requirements"
cache_location = ".requirements"
boot_contracts = ["pox", "costs-v1", "bns"]

[contracts.a-token-trait]
path = "contracts/borrow/traits/a-token-trait.clar"
clarity_version = 2
epoch = 2.4

# [contracts.stx-oracle]
# path = "contracts/borrow/mocks/stx-oracle.clar"
# clarity_version = 2
# epoch = 2.4

[contracts.xusd-oracle]
path = "contracts/borrow/mocks/xusd-oracle.clar"
clarity_version = 2
epoch = 2.4

[contracts.oracle]
path = "contracts/borrow/pool/oracle.clar"
clarity_version = 2
epoch = 2.4

[contracts.flashloan-script]
path = "contracts/borrow/mocks/flashloan-script.clar"
clarity_version = 2
epoch = 2.4

[contracts.flashloan-script-1]
path = "contracts/borrow/mocks/flashloan-script-1.clar"
clarity_version = 2
epoch = 2.4

[contracts.flashloan-script-2]
path = "contracts/borrow/mocks/flashloan-script-2.clar"
clarity_version = 2
epoch = 2.4

[contracts.pool-read]
path = "contracts/borrow/mocks/pool-read.clar"
clarity_version = 2
epoch = 2.4

[contracts.pool-read-supply]
path = "contracts/borrow/mocks/pool-read-supply.clar"
clarity_version = 2
epoch = 2.4

[contracts.pool-read-liquidation]
path = "contracts/borrow/mocks/pool-read-liquidation.clar"
clarity_version = 2
epoch = 2.4

# [contracts.governance-token-trait]
# path = "contracts/v2_sbtc/dao/traits/governance-token-trait.clar"
# clarity_version = 2
# epoch = 2.4

# [contracts.interest-rate-strategy-default]
# path = "contracts/v2_sbtc/pool/interest-rate-strategy-default.clar"
# clarity_version = 2
# epoch = 2.4

# [contracts.liquidity-vault-trait]
# path = "contracts/v2_sbtc/trait/liquidity-vault-trait.clar"
# clarity_version = 2
# epoch = 2.4

[contracts.lp-diko]
path = "contracts/borrow/mocks/lp-diko.clar"
clarity_version = 2
epoch = 2.4

[contracts.diko]
path = "contracts/borrow/mocks/diko.clar"
clarity_version = 2
epoch = 2.4

[contracts.zToken]
path = "contracts/borrow/token/zToken.clar"
clarity_version = 2
epoch = 2.4

[contracts.lp-sbtc]
path = "contracts/borrow/mocks/lp-sbtc.clar"
clarity_version = 2
epoch = 2.4

[contracts.sbtc]
path = "contracts/borrow/mocks/sbtc.clar"
clarity_version = 2
epoch = 2.4

[contracts.lp-ststx]
path = "contracts/borrow/mocks/lp-ststx.clar"
clarity_version = 2
epoch = 2.4

[contracts.ststx]
path = "contracts/borrow/mocks/ststx.clar"
clarity_version = 2
epoch = 2.4

[contracts.lp-wstx]
path = "contracts/borrow/mocks/lp-wstx.clar"
clarity_version = 2
epoch = 2.4

[contracts.wstx]
path = 'contracts/borrow/mocks/wstx.clar'
clarity_version = 2
epoch = 2.4

[contracts.lp-usda]
path = "contracts/borrow/mocks/lp-usda.clar"
clarity_version = 2
epoch = 2.4

[contracts.usda]
path = 'contracts/borrow/mocks/usda.clar'
clarity_version = 2
epoch = 2.4

[contracts.lp-xusd]
path = "contracts/borrow/mocks/lp-xusd.clar"
clarity_version = 2
epoch = 2.4

[contracts.xusd]
path = 'contracts/borrow/mocks/xusd.clar'
clarity_version = 2
epoch = 2.4

[contracts.supply-wrapped]
path = "contracts/borrow/pool/supply-wrapped.clar"
clarity_version = 2
epoch = 2.4

[contracts.pool-borrow]
path = "contracts/borrow/pool/pool-borrow.clar"
clarity_version = 2
epoch = 2.4

[contracts.pool-0-reserve]
path = "contracts/borrow/vaults/pool-0-reserve.clar"
clarity_version = 2
epoch = 2.4

[contracts.pool-vault]
path = "contracts/borrow/vaults/pool-vault.clar"
clarity_version = 2
epoch = 2.4

[contracts.liquidation-manager]
path = "contracts/borrow/pool/liquidation-manager.clar"
clarity_version = 2
epoch = 2.4

[contracts.lp-token-trait]
path = "contracts/v2_sbtc/trait/lp-token-trait.clar"
clarity_version = 2
epoch = 2.4

[contracts.ownable-trait]
path = "contracts/v2_sbtc/trait/ownable-trait.clar"
clarity_version = 2
epoch = 2.4

[contracts.ft-trait]
path = "contracts/v2_sbtc/trait/ft-trait.clar"
clarity_version = 2
epoch = 2.4

[contracts.ft-mint-trait]
path = "contracts/v2_sbtc/trait/ft-mint-trait.clar"
clarity_version = 2
epoch = 2.4

[contracts.vault-trait]
path = "contracts/borrow/traits/vault-trait.clar"
clarity_version = 2
epoch = 2.4

[contracts.oracle-trait]
path = "contracts/borrow/traits/oracle-trait.clar"
clarity_version = 2
epoch = 2.4

[contracts.flash-loan-trait]
path = "contracts/borrow/traits/flash-loan-trait.clar"
clarity_version = 2
epoch = 2.4

[contracts.pool-reserve-data]
path = "contracts/borrow/vaults/pool-reserve-data.clar"
clarity_version = 2
epoch = 2.4

[contracts.math]
path = "contracts/borrow/math/math.clar"
clarity_version = 2
epoch = 2.4

[repl]
costs_version = 1
parser_version = 2

[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
