[project]
name = "stacks-lending"
authors = []
description = ""
telemetry = false
requirements = [
  "SP3DX3H4FEYZJZ586MFBS25ZW3HZDMEW92260R2PR.Wrapped-Bitcoin",
  "SP2C2YFP12AJZB4MABJBAJ55XECVS7E4PMMZ89YZR.arkadiko-token",
  "SP2C2YFP12AJZB4MABJBAJ55XECVS7E4PMMZ89YZR.usda-token",
  "SP3K8BC0PPEVCV7NZ6QSRWPQ2JE9E5B6N3PA0KBR9.swap-helper-v1-03"
]
cache_dir = ".requirements"
cache_location=".requirements"
boot_contracts = ["pox", "costs-v1", "bns"]

[contracts.after-deployment]
path = "contracts/v2/after-deployment-simnet.clar"

[contracts.magic-protocol]
path = "contracts/v2/bitcoin/magic-protocol/magic-protocol.clar"

[contracts.magic-caller-ST1SJ3DTE5DN7X54YDH5D64R3BCB6A2AG2ZQ8YPD5]
path = "contracts/v2/bitcoin/magic-caller-ST1SJ3DTE5DN7X54YDH5D64R3BCB6A2AG2ZQ8YPD5.clar"

[contracts.magic-caller-ST3NBRSFKX28FQ2ZJ1MAKX58HKHSDGNV5N7R21XCP]
path = "contracts/v2/bitcoin/magic-caller-ST3NBRSFKX28FQ2ZJ1MAKX58HKHSDGNV5N7R21XCP.clar"

[contracts.clarity-bitcoin]
path = "contracts/v2/bitcoin/test/clarity-bitcoin.clar"

[contracts.coll-vault]
path = "contracts/v2/loan/coll-vault.clar"
depends_on = ["executor-dao"]

[contracts.coll-vault-trait]
path = "contracts/v2/trait/coll-vault-trait.clar"

[contracts.distribution-token-trait]
path = "contracts/v2/trait/distribution-token-trait.clar"

[contracts.distribution-token-cycles-trait]
path = "contracts/v2/trait/distribution-token-cycles-trait.clar"

[contracts.distribution-token-cycles-losses-trait]
path = "contracts/v2/trait/distribution-token-cycles-losses-trait.clar"

[contracts.executor-dao]
path = "contracts/v2/dao/executor-dao.clar"

[contracts.extension-trait]
path = "contracts/v2/dao/traits/extension-trait.clar"

[contracts.funding-vault]
path = "contracts/v2/loan/funding-vault.clar"

[contracts.funding-vault-trait]
path = "contracts/v2/trait/funding-vault-trait.clar"

[contracts.globals]
path = "contracts/v2/globals.clar"

[contracts.governance-token-trait]
path = "contracts/v2/dao/traits/governance-token-trait.clar"

[contracts.liquidity-vault-trait]
path = "contracts/v2/trait/liquidity-vault-trait.clar"

[contracts.liquidity-vault-v1-0]
path = "contracts/v2/pool/liquidity-vault-v1-0.clar"
depends_on = ["executor-dao"]

[contracts.loan-data]
path = "contracts/v2/loan/loan-data.clar"

[contracts.loan-v1-0]
path = "contracts/v2/loan/loan-v1-0.clar"

[contracts.lp-token]
path = "contracts/v2/token/lp-token.clar"
depends_on = ["executor-dao"]

[contracts.lp-token-0]
path = "contracts/v2/token/lp-token-0.clar"

[contracts.lp-token-trait]
path = "contracts/v2/trait/lp-token-trait.clar"

[contracts.ownable-trait]
path = "contracts/v2/trait/ownable-trait.clar"

[contracts.payment-fixed]
path = "contracts/v2/loan/payment-fixed.clar"

[contracts.payment-trait]
path = "contracts/v2/trait/payment-trait.clar"

[contracts.pool-v2-0]
path = "contracts/v2/pool/pool-v2-0.clar"

[contracts.proposal-trait]
path = "contracts/v2/dao/traits/proposal-trait.clar"

[contracts.protocol-treasury]
path = "contracts/v2/protocol-treasury.clar"

[contracts.read-data]
path = "contracts/v2/read-data.clar"

[contracts.restricted-token-trait]
path = "contracts/v2/trait/restricted-token-trait.clar"

[contracts.rewards-calc]
path = "contracts/v2/rewards-calc.clar"
depends_on = ["executor-dao"]

[contracts.rewards-calc-trait]
path = "contracts/v2/trait/rewards-calc-trait.clar"

[contracts.rewards-read]
path = "contracts/v2/rewards-read.clar"

[contracts.ft-trait]
path = "contracts/v2/trait/ft-trait.clar"

[contracts.xZest-token]
path = "contracts/v2/token/xZest-token.clar"

[contracts.sip-010-trait]
path = "contracts/v2/trait/sip-010-trait.clar"

[contracts.staking-pool]
path = "contracts/v2/pool/staking-pool.clar"

[contracts.cp-token]
path = "contracts/v2/token/cp-token.clar"
depends_on = ["executor-dao"]

[contracts.cp-rewards-token]
path = "contracts/v2/token/cp-rewards-token.clar"

[contracts.pool-data]
path = "contracts/v2/pool/pool-data.clar"

[contracts.cover-pool-v1-0]
path = "contracts/v2/pool/cover-pool-v1-0.clar"
depends_on = ["loan-v1-0", "zge000-governance-token", "read-data"]

[contracts.cover-vault]
path = "contracts/v2/pool/cover-vault.clar"

[contracts.cover-pool-data]
path = "contracts/v2/pool/cover-pool-data.clar"

[contracts.supplier-interface]
path = "contracts/v2/bitcoin/supplier-interface.clar"

[contracts.supplier-controller]
path = "contracts/v2/bitcoin/supplier-controller.clar"

[contracts.supplier-controller-trait]
path = "contracts/v2/trait/supplier-controller-trait.clar"

[contracts.swap-router]
path = "contracts/v2/swap-router.clar"

[contracts.swap-router-trait]
path = "contracts/v2/trait/swap-router-trait.clar"

[contracts.test-utils]
path = "contracts/v2/bitcoin/test/test-utils.clar"

[contracts.vault-trait]
path = "contracts/v2/trait/vault-trait.clar"

[contracts.withdrawal-manager]
path = 'contracts/v2/pool/withdrawal-manager.clar'
clarity_version = 1
epoch = 2.0

[contracts.Wrapped-Bitcoin]
path = "contracts/v2/token/Wrapped-Bitcoin-simnet.clar"

[contracts.Wrapped-USD]
path = "contracts/v2/token/Wrapped-USD.clar"

[contracts.zest-reward-dist]
path = "contracts/v2/token/zest-reward-dist.clar"
depends_on = ["executor-dao"]

[contracts.zge000-governance-token]
path = "contracts/v2/dao/extensions/zge000-governance-token.clar"
depends_on = ["executor-dao", "governance-token-trait", "ft-trait"]

[contracts.zge001-proposal-voting]
path = "contracts/v2/dao/extensions/zge001-proposal-voting.clar"
depends_on = ["executor-dao", "proposal-trait", "extension-trait", "governance-token-trait", "zge000-governance-token"]

[contracts.zge002-emergency-proposals]
path = "contracts/v2/dao/extensions/zge002-emergency-proposals.clar"
depends_on = ["executor-dao", "extension-trait", "zge001-proposal-voting"]

[contracts.zge003-emergency-execute]
path = "contracts/v2/dao/extensions/zge003-emergency-execute.clar"
depends_on = ["executor-dao", "extension-trait", "zge001-proposal-voting"]

[contracts.zgp000-bootstrap]
path = "contracts/v2/dao/proposals/zgp000-bootstrap-simnet.clar"
depends_on = ["executor-dao", "proposal-trait", "extension-trait", "zge000-governance-token", "zge001-proposal-voting", "zge002-emergency-proposals", "zge003-emergency-execute"]

[contracts.zgp001-kill-emergency-execute]
path = "contracts/v2/dao/proposals/zgp001-kill-emergency-execute.clar"
depends_on = ["zge003-emergency-execute", "executor-dao"]

[contracts.zgp002-onboard-borrower]
path = "contracts/v2/dao/proposals/zgp002-onboard-borrower.clar"
depends_on = ["executor-dao", "extension-trait"]

[contracts.zgp003-update-payment-fee]
path = "contracts/v2/dao/proposals/zgp003-update-payment-fee.clar"
depends_on = ["executor-dao", "extension-trait"]

[contracts.zgp004-add-pool-admin]
path = "contracts/v2/dao/proposals/zgp004-add-pool-admin.clar"
depends_on = ["executor-dao", "extension-trait"]

[contracts.zgp005-create-pool-1]
path = "contracts/v2/dao/proposals/zgp005-create-pool-1.clar"
depends_on = ["executor-dao", "extension-trait"]

[repl]
costs_version = 1
parser_version = 2

[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
