[project]
name = "stacks-lending"
authors = []
description = ""
telemetry = false
cache_dir = ".requirements"
cache_location = ".requirements"
boot_contracts = ["pox", "costs-v1", "bns"]

[[project.requirements]]
contract_id = 'SP2C2YFP12AJZB4MABJBAJ55XECVS7E4PMMZ89YZR.arkadiko-swap-v2-1'

[[project.requirements]]
contract_id = 'SP2C2YFP12AJZB4MABJBAJ55XECVS7E4PMMZ89YZR.arkadiko-oracle-v2-3'

[contracts.a-token-trait]
path = "contracts/borrow/production/traits/a-token-trait.clar"
clarity_version = 2
epoch = 2.4

[contracts.arkadiko-oracle]
path = "contracts/borrow/production/mocks/oracle/arkadiko-oracle.clar"
clarity_version = 2
epoch = 2.4

[contracts.diko-oracle]
path = "contracts/borrow/production/mocks/oracle/diko-oracle.clar"
clarity_version = 2
epoch = 2.4

[contracts.dex]
path = "contracts/borrow/production/mocks/oracle/dex.clar"
clarity_version = 2
epoch = 2.4

[contracts.xusd-oracle]
path = "contracts/borrow/production/mocks/oracle/xusd-oracle.clar"
clarity_version = 2
epoch = 2.4

[contracts.oracle]
path = "contracts/borrow/production/mocks/oracle/oracle.clar"
clarity_version = 2
epoch = 2.4

[contracts.update-asset]
path = "contracts/borrow/deployment_mainnet/update-asset.clar"
clarity_version = 2
epoch = 2.4

[contracts.flashloan-script]
path = "contracts/borrow/production/mocks/flashloan-scripts/flashloan-script.clar"
clarity_version = 2
epoch = 2.4

[contracts.flashloan-script-1]
path = "contracts/borrow/production/mocks/flashloan-scripts/flashloan-script-1.clar"
clarity_version = 2
epoch = 2.4

[contracts.flashloan-script-2]
path = "contracts/borrow/production/mocks/flashloan-scripts/flashloan-script-2.clar"
clarity_version = 2
epoch = 2.4

[contracts.pool-read]
path = "contracts/borrow/production/mocks/read-only/pool-read.clar"
clarity_version = 2
epoch = 2.4

[contracts.pool-read-supply]
path = "contracts/borrow/production/mocks/read-only/pool-read-supply.clar"
clarity_version = 2
epoch = 2.4

[contracts.pool-read-liquidation]
path = "contracts/borrow/production/mocks/read-only/pool-read-liquidation.clar"
clarity_version = 2
epoch = 2.4

[contracts.lp-diko]
path = "contracts/borrow/legacy/v0/mocks/ztoken/lp-diko.clar"
clarity_version = 2
epoch = 2.4

[contracts.lp-diko-v1]
path = "contracts/borrow/legacy/v1/mocks/ztoken/lp-diko.clar"
clarity_version = 2
epoch = 2.4

[contracts.lp-diko-v2]
path = "contracts/borrow/legacy/v1-2/mocks/ztoken/lp-diko.clar"
clarity_version = 2
epoch = 2.4

[contracts.diko]
path = "contracts/borrow/production/mocks/token/diko.clar"
clarity_version = 2
epoch = 2.4

[contracts.zToken]
path = "contracts/borrow/legacy/v0/token/zToken.clar"
clarity_version = 2
epoch = 2.4

[contracts.lp-sbtc]
path = "contracts/borrow/legacy/v0/mocks/ztoken/lp-sbtc.clar"
clarity_version = 2
epoch = 2.4

[contracts.sbtc]
path = "contracts/borrow/production/mocks/token/sbtc.clar"
clarity_version = 2
epoch = 2.4

[contracts.lp-ststx]
path = "contracts/borrow/legacy/v0/mocks/ztoken/lp-stSTX.clar"
clarity_version = 2
epoch = 2.4

[contracts.lp-ststx-v1]
path = "contracts/borrow/legacy/v1/mocks/ztoken/lp-ststx.clar"
clarity_version = 2
epoch = 2.4

[contracts.lp-ststx-v2]
path = "contracts/borrow/legacy/v1-2/mocks/ztoken/lp-ststx.clar"
clarity_version = 2
epoch = 2.4

# [contracts.lp-ststx-token]
# path = "contracts/borrow/production/mocks/ztoken/lp-ststx-token.clar"
# clarity_version = 2
# epoch = 2.4

[contracts.lp-sbtc-v1]
path = "contracts/borrow/legacy/v1/mocks/ztoken/lp-sbtc.clar"
clarity_version = 2
epoch = 2.4

[contracts.lp-sbtc-v2]
path = "contracts/borrow/legacy/v1-2/mocks/ztoken/lp-sbtc.clar"
clarity_version = 2
epoch = 2.4

[contracts.ststx]
path = "contracts/borrow/production/mocks/token/ststx.clar"
clarity_version = 2
epoch = 2.4

[contracts.lp-wstx]
path = "contracts/borrow/legacy/v0/mocks/ztoken/lp-wstx.clar"
clarity_version = 2
epoch = 2.4

[contracts.lp-wstx-v1]
path = "contracts/borrow/legacy/v1/mocks/ztoken/lp-wstx.clar"
clarity_version = 2
epoch = 2.4

[contracts.lp-wstx-v2]
path = "contracts/borrow/legacy/v1-2/mocks/ztoken/lp-wstx.clar"
clarity_version = 2
epoch = 2.4

[contracts.wstx]
path = 'contracts/borrow/production/mocks/token/wstx.clar'
clarity_version = 2
epoch = 2.4

[contracts.lp-usda]
path = "contracts/borrow/legacy/v0/mocks/ztoken/lp-USDA.clar"
clarity_version = 2
epoch = 2.4

[contracts.lp-usda-v1]
path = "contracts/borrow/legacy/v1/mocks/ztoken/lp-usda.clar"
clarity_version = 2
epoch = 2.4

[contracts.lp-usda-v2]
path = "contracts/borrow/legacy/v1-2/mocks/ztoken/lp-usda.clar"
clarity_version = 2
epoch = 2.4

[contracts.usda]
path = 'contracts/borrow/production/mocks/token/usda.clar'
clarity_version = 2
epoch = 2.4

[contracts.lp-xusd]
path = "contracts/borrow/legacy/v0/mocks/ztoken/lp-xUSD.clar"
clarity_version = 2
epoch = 2.4

[contracts.lp-xusd-v1]
path = "contracts/borrow/legacy/v1/mocks/ztoken/lp-xusd.clar"
clarity_version = 2
epoch = 2.4

[contracts.lp-xusd-v2]
path = "contracts/borrow/legacy/v1-2/mocks/ztoken/lp-xusd.clar"
clarity_version = 2
epoch = 2.4

[contracts.xusd]
path = 'contracts/borrow/production/mocks/token/xusd.clar'
clarity_version = 2
epoch = 2.4

[contracts.borrow-helper]
path = "contracts/borrow/legacy/v0/mocks/wrappers/borrow-helper.clar"
clarity_version = 2
epoch = 2.4

[contracts.borrow-helper-v1-2]
path = "contracts/borrow/legacy/v1-2/wrappers/borrow-helper.clar"
clarity_version = 2
epoch = 2.4

[contracts.borrow-helper-v1-3]
path = "contracts/borrow/legacy/v1-2/wrappers/borrow-helper-v1-1.clar"
clarity_version = 2
epoch = 2.4

[contracts.pool-borrow]
path = "contracts/borrow/legacy/v0/pool/pool-borrow.clar"
clarity_version = 2
epoch = 2.4

[contracts.pool-borrow-v1-1]
path = "contracts/borrow/legacy/v1/pool/pool-borrow.clar"
clarity_version = 2
epoch = 2.4

[contracts.pool-borrow-v1-2]
path = "contracts/borrow/legacy/v1-2/pool/pool-borrow.clar"
clarity_version = 2
epoch = 2.4

[contracts.pool-0-reserve]
path = "contracts/borrow/production/vaults/pool-0-reserve.clar"
clarity_version = 2
epoch = 2.4

[contracts.pool-0-reserve-v1-2]
path = "contracts/borrow/legacy/v1-2/vaults/pool-0-reserve.clar"
clarity_version = 2
epoch = 2.4

[contracts.pool-vault]
path = "contracts/borrow/production/vaults/pool-vault.clar"
clarity_version = 2
epoch = 2.4

[contracts.liquidation-manager]
path = "contracts/borrow/legacy/v0/pool/liquidation-manager.clar"
clarity_version = 2
epoch = 2.4

[contracts.liquidation-manager-v1-1]
path = "contracts/borrow/legacy/v1/pool/liquidation-manager.clar"
clarity_version = 2
epoch = 2.4

[contracts.liquidation-manager-v1-2]
path = "contracts/borrow/legacy/v1-2/pool/liquidation-manager.clar"
clarity_version = 2
epoch = 2.4

[contracts.ownable-trait]
path = "contracts/borrow/production/traits/ownable-trait.clar"
clarity_version = 2
epoch = 2.4

[contracts.ft-trait]
path = "contracts/borrow/production/traits/ft-trait.clar"
clarity_version = 2
epoch = 2.4

[contracts.ft-mint-trait]
path = "contracts/borrow/production/traits/ft-mint-trait.clar"
clarity_version = 2
epoch = 2.4

[contracts.redeemeable-trait]
path = "contracts/borrow/legacy/v0/traits/redeemeable-trait.clar"
clarity_version = 2
epoch = 2.4

[contracts.redeemeable-trait-v1-2]
path = "contracts/borrow/production/traits/redeemeable-trait-v1-2.clar"
clarity_version = 2
epoch = 2.4

[contracts.vault-trait]
path = "contracts/borrow/production/traits/vault-trait.clar"
clarity_version = 2
epoch = 2.4

[contracts.oracle-trait]
path = "contracts/borrow/production/traits/oracle-trait.clar"
clarity_version = 2
epoch = 2.4

[contracts.flash-loan-trait]
path = "contracts/borrow/production/traits/flash-loan-trait.clar"
clarity_version = 2
epoch = 2.4

[contracts.pool-reserve-data]
path = "contracts/borrow/production/reserve-data/pool-reserve-data.clar"
clarity_version = 2
epoch = 2.4

[contracts.pool-reserve-data-1]
path = "contracts/borrow/production/reserve-data/pool-reserve-data-1.clar"
clarity_version = 2
epoch = 2.4

[contracts.math]
path = "contracts/borrow/legacy/v0/math/math.clar"
clarity_version = 2
epoch = 2.4

[contracts.math-v1-2]
path = "contracts/borrow/legacy/v1-2/math/math.clar"
clarity_version = 2
epoch = 2.4

[repl]
costs_version = 1
parser_version = 2

[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
