[project]
name = "stacks-lending"
authors = []
description = ""
telemetry = false
requirements = [
  "SP3DX3H4FEYZJZ586MFBS25ZW3HZDMEW92260R2PR.Wrapped-Bitcoin",
  "SP2C2YFP12AJZB4MABJBAJ55XECVS7E4PMMZ89YZR.arkadiko-token",
  "SP2C2YFP12AJZB4MABJBAJ55XECVS7E4PMMZ89YZR.usda-token",
  "SP3K8BC0PPEVCV7NZ6QSRWPQ2JE9E5B6N3PA0KBR9.swap-helper-v1-03",
]
cache_dir = ".requirements"
cache_location = ".requirements"
boot_contracts = ["pox", "costs-v1", "bns"]

[contracts.after-deployment]
path = "contracts/v2_sbtc/after-deployment-simnet.clar"
clarity_version = 2
epoch = 2.1

[contracts.magic-protocol]
path = "contracts/v2_sbtc/bitcoin/magic-protocol/magic-protocol.clar"
clarity_version = 2
epoch = 2.1

# [contracts.magic-caller]
# path = "contracts/v2_sbtc/bitcoin/magic-caller.clar"
# clarity_version = 2
# epoch = 2.1

# [contracts.magic-caller-ST3NBRSFKX28FQ2ZJ1MAKX58HKHSDGNV5N7R21XCP]
# path = "contracts/v2_sbtc/bitcoin/magic-caller-ST3NBRSFKX28FQ2ZJ1MAKX58HKHSDGNV5N7R21XCP.clar"

[contracts.clarity-bitcoin]
path = "contracts/v2_sbtc/bitcoin/test/clarity-bitcoin-v2-1.clar"
clarity_version = 2
epoch = 2.1

[contracts.coll-vault]
path = "contracts/v2_sbtc/loan/coll-vault.clar"
clarity_version = 2
epoch = 2.1

[contracts.coll-vault-trait]
path = "contracts/v2_sbtc/trait/coll-vault-trait.clar"
clarity_version = 2
epoch = 2.1

[contracts.distribution-token-trait]
path = "contracts/v2_sbtc/trait/distribution-token-trait.clar"
clarity_version = 2
epoch = 2.1

[contracts.distribution-token-cycles-trait]
path = "contracts/v2_sbtc/trait/distribution-token-cycles-trait.clar"
clarity_version = 2
epoch = 2.1

[contracts.distribution-token-cycles-losses-trait]
path = "contracts/v2_sbtc/trait/distribution-token-cycles-losses-trait.clar"
clarity_version = 2
epoch = 2.1

[contracts.executor-dao]
path = "contracts/v2_sbtc/dao/executor-dao.clar"
clarity_version = 2
epoch = 2.1

[contracts.extension-trait]
path = "contracts/v2_sbtc/dao/traits/extension-trait.clar"
clarity_version = 2
epoch = 2.1

[contracts.funding-vault]
path = "contracts/v2_sbtc/loan/funding-vault.clar"
clarity_version = 2
epoch = 2.1

[contracts.funding-vault-trait]
path = "contracts/v2_sbtc/trait/funding-vault-trait.clar"
clarity_version = 2
epoch = 2.1

[contracts.globals]
path = "contracts/v2_sbtc/globals.clar"
clarity_version = 2
epoch = 2.1

[contracts.governance-token-trait]
path = "contracts/v2_sbtc/dao/traits/governance-token-trait.clar"
clarity_version = 2
epoch = 2.1

[contracts.liquidity-vault-trait]
path = "contracts/v2_sbtc/trait/liquidity-vault-trait.clar"
clarity_version = 2
epoch = 2.1

[contracts.liquidity-vault-v1-0]
path = "contracts/v2_sbtc/pool/liquidity-vault-v1-0.clar"
clarity_version = 2
epoch = 2.1

[contracts.loan-data]
path = "contracts/v2_sbtc/loan/loan-data.clar"
clarity_version = 2
epoch = 2.1

[contracts.loan-v1-0]
path = "contracts/v2_sbtc/loan/loan-v1-0.clar"
clarity_version = 2
epoch = 2.1

[contracts.lp-token]
path = "contracts/v2_sbtc/token/lp-token.clar"
clarity_version = 2
epoch = 2.1

[contracts.lp-token-0]
path = "contracts/v2_sbtc/token/lp-token-0.clar"
clarity_version = 2
epoch = 2.1

[contracts.lp-token-trait]
path = "contracts/v2_sbtc/trait/lp-token-trait.clar"
clarity_version = 2
epoch = 2.1

[contracts.ownable-trait]
path = "contracts/v2_sbtc/trait/ownable-trait.clar"
clarity_version = 2
epoch = 2.1

[contracts.payment-fixed]
path = "contracts/v2_sbtc/loan/payment-fixed.clar"
clarity_version = 2
epoch = 2.1

[contracts.payment-trait]
path = "contracts/v2_sbtc/trait/payment-trait.clar"
clarity_version = 2
epoch = 2.1

[contracts.pool-v2-0]
path = "contracts/v2_sbtc/pool/pool-v2-0.clar"
clarity_version = 2
epoch = 2.1

[contracts.proposal-trait]
path = "contracts/v2_sbtc/dao/traits/proposal-trait.clar"
clarity_version = 2
epoch = 2.1

[contracts.protocol-treasury]
path = "contracts/v2_sbtc/protocol-treasury.clar"
clarity_version = 2
epoch = 2.1

[contracts.read-data]
path = "contracts/v2_sbtc/read-data.clar"
clarity_version = 2
epoch = 2.1

[contracts.restricted-token-trait]
path = "contracts/v2_sbtc/trait/restricted-token-trait.clar"
clarity_version = 2
epoch = 2.1

[contracts.rewards-calc]
path = "contracts/v2_sbtc/rewards-calc.clar"
clarity_version = 2
epoch = 2.1

[contracts.rewards-calc-trait]
path = "contracts/v2_sbtc/trait/rewards-calc-trait.clar"
clarity_version = 2
epoch = 2.1

[contracts.rewards-read]
path = "contracts/v2_sbtc/rewards-read.clar"
clarity_version = 2
epoch = 2.1

[contracts.ft-trait]
path = "contracts/v2_sbtc/trait/ft-trait.clar"
clarity_version = 2
epoch = 2.1

[contracts.xZest-token]
path = "contracts/v2_sbtc/token/xZest-token.clar"
clarity_version = 2
epoch = 2.1

[contracts.sBTC]
path = "contracts/v2_sbtc/token/sBTC.clar"
clarity_version = 2
epoch = 2.1

[contracts.sbtc-deposit-caller]
path = "contracts/v2_sbtc/bitcoin/sbtc-deposit-caller.clar"
clarity_version = 2
epoch = 2.1

[contracts.sip-010-trait]
path = "contracts/v2_sbtc/trait/sip-010-trait.clar"
clarity_version = 2
epoch = 2.1

[contracts.staking-pool]
path = "contracts/v2_sbtc/pool/staking-pool.clar"
clarity_version = 2
epoch = 2.1

[contracts.cp-token]
path = "contracts/v2_sbtc/token/cp-token.clar"
clarity_version = 2
epoch = 2.1

[contracts.cp-rewards-token]
path = "contracts/v2_sbtc/token/cp-rewards-token.clar"
clarity_version = 2
epoch = 2.1

[contracts.pool-data]
path = "contracts/v2_sbtc/pool/pool-data.clar"
clarity_version = 2
epoch = 2.1

[contracts.cover-pool-v1-0]
path = "contracts/v2_sbtc/pool/cover-pool-v1-0.clar"
clarity_version = 2
epoch = 2.1

[contracts.cover-vault]
path = "contracts/v2_sbtc/pool/cover-vault.clar"
clarity_version = 2
epoch = 2.1

[contracts.cover-pool-data]
path = "contracts/v2_sbtc/pool/cover-pool-data.clar"
clarity_version = 2
epoch = 2.1

[contracts.supplier-interface]
path = "contracts/v2_sbtc/bitcoin/supplier-interface.clar"
clarity_version = 2
epoch = 2.1

[contracts.supplier-controller]
path = "contracts/v2_sbtc/bitcoin/supplier-controller.clar"
clarity_version = 2
epoch = 2.1

[contracts.supplier-controller-trait]
path = "contracts/v2_sbtc/trait/supplier-controller-trait.clar"
clarity_version = 2
epoch = 2.1

[contracts.swap-router]
path = "contracts/v2_sbtc/swap-router.clar"
clarity_version = 2
epoch = 2.1

[contracts.swap-router-trait]
path = "contracts/v2_sbtc/trait/swap-router-trait.clar"
clarity_version = 2
epoch = 2.1

[contracts.test-utils]
path = "contracts/v2_sbtc/bitcoin/test/test-utils.clar"
clarity_version = 2
epoch = 2.1

[contracts.vault-trait]
path = "contracts/v2_sbtc/trait/vault-trait.clar"
clarity_version = 2
epoch = 2.1

[contracts.withdrawal-data]
path = 'contracts/v2_sbtc/pool/withdrawal-data.clar'
clarity_version = 2
epoch = 2.1

[contracts.withdrawal-manager]
path = 'contracts/v2_sbtc/pool/withdrawal-manager.clar'
clarity_version = 2
epoch = 2.1

[contracts.Wrapped-Bitcoin]
path = "contracts/v2_sbtc/token/Wrapped-Bitcoin-simnet.clar"
clarity_version = 2
epoch = 2.1

[contracts.Wrapped-USD]
path = "contracts/v2_sbtc/token/Wrapped-USD.clar"
clarity_version = 2
epoch = 2.1

[contracts.zest-reward-dist]
path = "contracts/v2_sbtc/token/zest-reward-dist.clar"
clarity_version = 2
epoch = 2.1

[contracts.zge000-governance-token]
path = "contracts/v2_sbtc/dao/extensions/zge000-governance-token.clar"
clarity_version = 2
epoch = 2.1

[contracts.zge001-proposal-voting]
path = "contracts/v2_sbtc/dao/extensions/zge001-proposal-voting.clar"
clarity_version = 2
epoch = 2.1

[contracts.zge002-emergency-proposals]
path = "contracts/v2_sbtc/dao/extensions/zge002-emergency-proposals.clar"
clarity_version = 2
epoch = 2.1

[contracts.zge003-emergency-execute]
path = "contracts/v2_sbtc/dao/extensions/zge003-emergency-execute.clar"
clarity_version = 2
epoch = 2.1

[contracts.zgp000-bootstrap]
path = "contracts/v2_sbtc/dao/proposals/zgp000-bootstrap-simnet.clar"
clarity_version = 2
epoch = 2.1

[contracts.zgp001-kill-emergency-execute]
path = "contracts/v2_sbtc/dao/proposals/zgp001-kill-emergency-execute.clar"
clarity_version = 2
epoch = 2.1

[contracts.zgp002-onboard-borrower]
path = "contracts/v2_sbtc/dao/proposals/zgp002-onboard-borrower.clar"
clarity_version = 2
epoch = 2.1

[contracts.zgp003-update-payment-fee]
path = "contracts/v2_sbtc/dao/proposals/zgp003-update-payment-fee.clar"
clarity_version = 2
epoch = 2.1

[contracts.zgp004-add-pool-admin]
path = "contracts/v2_sbtc/dao/proposals/zgp004-add-pool-admin.clar"
clarity_version = 2
epoch = 2.1

[contracts.zgp005-create-pool-1]
path = "contracts/v2_sbtc/dao/proposals/zgp005-create-pool-1.clar"
clarity_version = 2
epoch = 2.1

[repl]
costs_version = 1
parser_version = 2

[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
