[project]
name = 'stacks-lending'
description = ''
authors = []
telemetry = false
cache_dir = '.cache'
requirements = []
[contracts.Wrapped-Bitcoin]
path = 'contracts/token/Wrapped-Bitcoin.clar'
clarity_version = 1
epoch = 2.0

[contracts.Wrapped-USD]
path = 'contracts/token/Wrapped-USD.clar'
clarity_version = 1
epoch = 2.0

[contracts.after-deployment]
path = 'contracts/after-deployment-testnet.clar'
clarity_version = 1
epoch = 2.0

[contracts.clarity-bitcoin]
path = 'contracts/bitcoin/magic-protocol/clarity-bitcoin.clar'
clarity_version = 1
epoch = 2.0

[contracts.coll-vault]
path = 'contracts/loan/coll-vault.clar'
clarity_version = 1
epoch = 2.0

[contracts.coll-vault-trait]
path = 'contracts/trait/coll-vault-trait.clar'
clarity_version = 1
epoch = 2.0

[contracts.cover-pool-data]
path = 'contracts/pool/cover-pool-data.clar'
clarity_version = 1
epoch = 2.0

[contracts.cover-pool-v1-0]
path = 'contracts/pool/cover-pool-v1-0.clar'
clarity_version = 1
epoch = 2.0

[contracts.cover-vault]
path = 'contracts/pool/cover-vault.clar'
clarity_version = 1
epoch = 2.0

[contracts.cp-rewards-token]
path = 'contracts/token/cp-rewards-token.clar'
clarity_version = 1
epoch = 2.0

[contracts.cp-token]
path = 'contracts/token/cp-token.clar'
clarity_version = 1
epoch = 2.0

[contracts.distribution-token-cycles-losses-trait]
path = 'contracts/trait/distribution-token-cycles-losses-trait.clar'
clarity_version = 1
epoch = 2.0

[contracts.distribution-token-cycles-trait]
path = 'contracts/trait/distribution-token-cycles-trait.clar'
clarity_version = 1
epoch = 2.0

[contracts.distribution-token-trait]
path = 'contracts/trait/distribution-token-trait.clar'
clarity_version = 1
epoch = 2.0

[contracts.executor-dao]
path = 'contracts/dao/executor-dao.clar'
clarity_version = 1
epoch = 2.0

[contracts.extension-trait]
path = 'contracts/dao/traits/extension-trait.clar'
clarity_version = 1
epoch = 2.0

[contracts.ft-trait]
path = 'contracts/trait/ft-trait.clar'
clarity_version = 1
epoch = 2.0

[contracts.funding-vault]
path = 'contracts/loan/funding-vault.clar'
clarity_version = 1
epoch = 2.0

[contracts.funding-vault-trait]
path = 'contracts/trait/funding-vault-trait.clar'
clarity_version = 1
epoch = 2.0

[contracts.globals]
path = 'contracts/globals.clar'
clarity_version = 1
epoch = 2.0

[contracts.governance-token-trait]
path = 'contracts/dao/traits/governance-token-trait.clar'
clarity_version = 1
epoch = 2.0

[contracts.liquidity-vault-trait]
path = 'contracts/trait/liquidity-vault-trait.clar'
clarity_version = 1
epoch = 2.0

[contracts.liquidity-vault-v1-0]
path = 'contracts/pool/liquidity-vault-v1-0.clar'
clarity_version = 1
epoch = 2.0

[contracts.loan-data]
path = 'contracts/loan/loan-data.clar'
clarity_version = 1
epoch = 2.0

[contracts.loan-v1-0]
path = 'contracts/loan/loan-v1-0.clar'
clarity_version = 1
epoch = 2.0

[contracts.lp-token]
path = 'contracts/token/lp-token.clar'
clarity_version = 1
epoch = 2.0

[contracts.lp-token-trait]
path = 'contracts/trait/lp-token-trait.clar'
clarity_version = 1
epoch = 2.0

[contracts.magic-protocol]
path = 'contracts/bitcoin/magic-protocol/magic-protocol.clar'
clarity_version = 1
epoch = 2.0

[contracts.ownable-trait]
path = 'contracts/trait/ownable-trait.clar'
clarity_version = 1
epoch = 2.0

[contracts.payment-fixed]
path = 'contracts/loan/payment-fixed.clar'
clarity_version = 1
epoch = 2.0

[contracts.payment-trait]
path = 'contracts/trait/payment-trait.clar'
clarity_version = 1
epoch = 2.0

[contracts.pool-data]
path = 'contracts/pool/pool-data.clar'
clarity_version = 1
epoch = 2.0

[contracts.pool-v1-0]
path = 'contracts/pool/pool-v1-0.clar'
clarity_version = 1
epoch = 2.0

[contracts.proposal-trait]
path = 'contracts/dao/traits/proposal-trait.clar'
clarity_version = 1
epoch = 2.0

[contracts.protocol-treasury]
path = 'contracts/protocol-treasury.clar'
clarity_version = 1
epoch = 2.0

[contracts.read-data]
path = 'contracts/read-data.clar'
clarity_version = 1
epoch = 2.0

[contracts.restricted-token-trait]
path = 'contracts/trait/restricted-token-trait.clar'
clarity_version = 1
epoch = 2.0

[contracts.rewards-calc]
path = 'contracts/rewards-calc.clar'
clarity_version = 1
epoch = 2.0

[contracts.rewards-calc-trait]
path = 'contracts/trait/rewards-calc-trait.clar'
clarity_version = 1
epoch = 2.0

[contracts.rewards-read]
path = 'contracts/rewards-read.clar'
clarity_version = 1
epoch = 2.0

[contracts.staking-pool]
path = 'contracts/pool/staking-pool.clar'
clarity_version = 1
epoch = 2.0

[contracts.supplier-interface]
path = 'contracts/bitcoin/supplier-interface.clar'
clarity_version = 1
epoch = 2.0

[contracts.swap-router]
path = 'contracts/swap-router.clar'
clarity_version = 1
epoch = 2.0

[contracts.swap-router-trait]
path = 'contracts/trait/swap-router-trait.clar'
clarity_version = 1
epoch = 2.0

[contracts.vault-trait]
path = 'contracts/trait/vault-trait.clar'
clarity_version = 1
epoch = 2.0

[contracts.withdrawal-manager]
path = 'contracts/pool/withdrawal-manager.clar'
clarity_version = 1
epoch = 2.0

[contracts.xZest-token]
path = 'contracts/token/xZest-token.clar'
clarity_version = 1
epoch = 2.0

[contracts.zest-reward-dist]
path = 'contracts/token/zest-reward-dist.clar'
clarity_version = 1
epoch = 2.0

[contracts.zge000-governance-token]
path = 'contracts/dao/extensions/zge000-governance-token.clar'
clarity_version = 1
epoch = 2.0

[contracts.zge001-proposal-voting]
path = 'contracts/dao/extensions/zge001-proposal-voting.clar'
clarity_version = 1
epoch = 2.0

[contracts.zge002-emergency-proposals]
path = 'contracts/dao/extensions/zge002-emergency-proposals.clar'
clarity_version = 1
epoch = 2.0

[contracts.zge003-emergency-execute]
path = 'contracts/dao/extensions/zge003-emergency-execute.clar'
clarity_version = 1
epoch = 2.0

[contracts.zgp000-bootstrap]
path = 'contracts/dao/proposals/zgp000-bootstrap.clar'
clarity_version = 1
epoch = 2.0

[contracts.zgp001-kill-emergency-execute]
path = 'contracts/dao/proposals/zgp001-kill-emergency-execute.clar'
clarity_version = 1
epoch = 2.0
[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
