[project]
name = "stacks-lending"
authors = []
description = ""
telemetry = false
cache_dir = ".requirements"
cache_location = ".requirements"
boot_contracts = ["pox", "costs-v1", "bns"]

[[project.requirements]]
contract_id = 'SP2C2YFP12AJZB4MABJBAJ55XECVS7E4PMMZ89YZR.arkadiko-swap-v2-1'

[[project.requirements]]
contract_id = 'SP2C2YFP12AJZB4MABJBAJ55XECVS7E4PMMZ89YZR.arkadiko-oracle-v2-3'

[contracts.a-token-trait]
path = "contracts/borrow/production/traits/a-token-trait.clar"
clarity_version = 2
epoch = 2.4

[contracts.arkadiko-oracle]
path = "contracts/borrow/production/mocks/oracle/arkadiko-oracle.clar"
clarity_version = 2
epoch = 2.4

[contracts.diko-oracle]
path = "contracts/borrow/production/mocks/oracle/diko-oracle.clar"
clarity_version = 2
epoch = 2.4

[contracts.dex]
path = "contracts/borrow/production/mocks/oracle/dex.clar"
clarity_version = 2
epoch = 2.4

[contracts.xusd-oracle]
path = "contracts/borrow/production/mocks/oracle/xusd-oracle.clar"
clarity_version = 2
epoch = 2.4

[contracts.incentives-read]
path = "contracts/borrow/production/rewards/incentives-read.clar"
clarity_version = 3
epoch = 3.0

[contracts.oracle]
path = "contracts/borrow/production/mocks/oracle/oracle.clar"
clarity_version = 2
epoch = 2.4

# [contracts.update-asset]
# path = "contracts/borrow/deployment_mainnet/update-asset.clar"
# clarity_version = 2
# epoch = 2.4

[contracts.flashloan-script]
path = "contracts/borrow/production/mocks/flashloan-scripts/flashloan-script.clar"
clarity_version = 2
epoch = 2.4

[contracts.flashloan-script-1]
path = "contracts/borrow/production/mocks/flashloan-scripts/flashloan-script-1.clar"
clarity_version = 2
epoch = 2.4

[contracts.flashloan-script-2]
path = "contracts/borrow/production/mocks/flashloan-scripts/flashloan-script-2.clar"
clarity_version = 2
epoch = 2.4

[contracts.diko]
path = "contracts/borrow/production/mocks/token/diko.clar"
clarity_version = 2
epoch = 2.4

[contracts.zToken]
path = "contracts/borrow/legacy/v0/token/zToken.clar"
clarity_version = 2
epoch = 2.4

[contracts.sbtc]
path = "contracts/borrow/production/mocks/token/sbtc.clar"
clarity_version = 2
epoch = 2.4

[contracts.lp-diko-token]
path = "contracts/borrow/production/mocks/ztoken/lp-diko-token.clar"
clarity_version = 2
epoch = 2.4

[contracts.lp-ststx-token]
path = "contracts/borrow/production/mocks/ztoken/lp-ststx-token.clar"
clarity_version = 2
epoch = 2.4

[contracts.lp-sbtc-token]
path = "contracts/borrow/production/mocks/ztoken/lp-sbtc-token.clar"
clarity_version = 2
epoch = 2.4

[contracts.lp-usda-token]
path = "contracts/borrow/production/mocks/ztoken/lp-usda-token.clar"
clarity_version = 2
epoch = 2.4

[contracts.lp-wstx-token]
path = "contracts/borrow/production/mocks/ztoken/lp-wstx-token.clar"
clarity_version = 2
epoch = 2.4

[contracts.lp-xusd-token]
path = "contracts/borrow/production/mocks/ztoken/lp-xusd-token.clar"
clarity_version = 2
epoch = 2.4

[contracts.lp-ststx]
path = "contracts/borrow/legacy/v0/mocks/ztoken/lp-stSTX.clar"
clarity_version = 2
epoch = 2.4

[contracts.lp-ststx-v1]
path = "contracts/borrow/legacy/v1/mocks/ztoken/lp-ststx.clar"
clarity_version = 2
epoch = 2.4

[contracts.lp-ststx-v2]
path = "contracts/borrow/legacy/v1-2/mocks/ztoken/lp-ststx.clar"
clarity_version = 2
epoch = 2.4

[contracts.lp-ststx-v3]
path = "contracts/borrow/production/mocks/ztoken/lp-ststx.clar"
clarity_version = 3
epoch = 3.0

[contracts.lp-diko-v3]
path = "contracts/borrow/production/mocks/ztoken/lp-diko.clar"
clarity_version = 3
epoch = 3.0

[contracts.lp-sbtc-v3]
path = "contracts/borrow/production/mocks/ztoken/lp-sbtc.clar"
clarity_version = 3
epoch = 3.0

[contracts.lp-usda-v3]
path = "contracts/borrow/production/mocks/ztoken/lp-usda.clar"
clarity_version = 3
epoch = 3.0

[contracts.lp-wstx-v3]
path = "contracts/borrow/production/mocks/ztoken/lp-wstx.clar"
clarity_version = 3
epoch = 3.0

[contracts.lp-xusd-v3]
path = "contracts/borrow/production/mocks/ztoken/lp-xusd.clar"
clarity_version = 3
epoch = 3.0


[contracts.xusd]
path = 'contracts/borrow/production/mocks/token/xusd.clar'
clarity_version = 2
epoch = 2.4

[contracts.usda]
path = 'contracts/borrow/production/mocks/token/usda.clar'
clarity_version = 2
epoch = 2.4

[contracts.wstx]
path = 'contracts/borrow/production/mocks/token/wstx.clar'
clarity_version = 2
epoch = 2.4

[contracts.ownable-trait]
path = "contracts/borrow/production/traits/ownable-trait.clar"
clarity_version = 2
epoch = 2.4

[contracts.ststx]
path = "contracts/borrow/production/mocks/token/ststx.clar"
clarity_version = 2
epoch = 2.4

[contracts.borrow-helper]
path = "contracts/borrow/legacy/v0/mocks/wrappers/borrow-helper.clar"
clarity_version = 2
epoch = 2.4

[contracts.borrow-helper-v2-1]
path = "contracts/borrow/production/wrappers/borrow-helper.clar"
clarity_version = 3
epoch = 3.0


[contracts.pool-borrow]
path = "contracts/borrow/legacy/v0/pool/pool-borrow.clar"
clarity_version = 2
epoch = 2.4

[contracts.pool-borrow-v1-1]
path = "contracts/borrow/legacy/v1/pool/pool-borrow.clar"
clarity_version = 2
epoch = 2.4

[contracts.pool-borrow-v1-2]
path = "contracts/borrow/legacy/v1-2/pool/pool-borrow.clar"
clarity_version = 2
epoch = 2.4

[contracts.pool-borrow-v2-1]
path = "contracts/borrow/production/pool/pool-borrow.clar"
clarity_version = 3
epoch = 3.0

[contracts.pool-0-reserve]
path = "contracts/borrow/production/vaults/pool-0-reserve.clar"
clarity_version = 2
epoch = 2.4

[contracts.pool-0-reserve-v1-2]
path = "contracts/borrow/legacy/v1-2/vaults/pool-0-reserve.clar"
clarity_version = 2
epoch = 2.4

[contracts.pool-0-reserve-v2-0]
path = "contracts/borrow/production/vaults/pool-0-reserve-v2-0.clar"
clarity_version = 3
epoch = 3.0

[contracts.user-data]
path = "contracts/borrow/production/reads/user-data.clar"
clarity_version = 3
epoch = 3.0


# [contracts.reserve-data]
# path = "contracts/borrow/production/reads/reserve-data.clar"
# clarity_version = 3
# epoch = 3.0

[contracts.incentives-vault]
path = "contracts/borrow/production/mocks/rewards/incentives-vault.clar"
clarity_version = 3
epoch = 3.0


[contracts.pool-vault]
path = "contracts/borrow/production/vaults/pool-vault.clar"
clarity_version = 2
epoch = 2.4




# [contracts.e-mode-stx-enable]
# path = "contracts/borrow/deployment_mainnet/upgrades/emode/e-mode-stx-enable.clar"
# clarity_version = 3
# epoch = 3.0

# [contracts.borrow-sbtc]
# path = "contracts/borrow/deployment_mainnet/upgrades/zsbtc/sbtc-deployment/borrow-sbtc.clar"
# clarity_version = 3
# epoch = 3.0

[contracts.liquidation-manager]
path = "contracts/borrow/legacy/v0/pool/liquidation-manager.clar"
clarity_version = 2
epoch = 2.4

[contracts.liquidation-manager-v1-1]
path = "contracts/borrow/legacy/v1/pool/liquidation-manager.clar"
clarity_version = 2
epoch = 2.4

[contracts.liquidation-manager-v1-2]
path = "contracts/borrow/legacy/v1-2/pool/liquidation-manager.clar"
clarity_version = 2
epoch = 2.4

[contracts.liquidation-manager-v2-0]
path = "contracts/borrow/production/pool/liquidation-manager.clar"
clarity_version = 3
epoch = 3.0

[contracts.liquidation-manager-v2-0-1]
path = "contracts/borrow/legacy/v2-0-1/pool/liquidation-manager.clar"
clarity_version = 3
epoch = 3.0

[contracts.liquidation-manager-v2-1]
path = "contracts/borrow/production/pool/liquidation-manager.clar"
clarity_version = 3
epoch = 3.0

[contracts.incentives]
path = "contracts/borrow/production/mocks/rewards/incentives.clar"
clarity_version = 3
epoch = 3.0

[contracts.incentives-v2-0]
path = "contracts/borrow/production/mocks/rewards/incentives.clar"
clarity_version = 3
epoch = 3.0

[contracts.incentives-v2-1]
path = "contracts/borrow/production/mocks/rewards/incentives.clar"
clarity_version = 3
epoch = 3.0

[contracts.incentives-2]
path = "contracts/borrow/production/mocks/rewards/incentives-2.clar"
clarity_version = 3
epoch = 3.0

[contracts.incentives-dummy]
path = "contracts/borrow/production/mocks/rewards/incentives-dummy.clar"
clarity_version = 3
epoch = 3.0

[contracts.rewards-data]
path = "contracts/borrow/production/reserve-data/rewards-data.clar"
clarity_version = 3
epoch = 3.0


[contracts.flashloan-data]
path = "contracts/borrow/production/reserve-data/flashloan-data.clar"
clarity_version = 2
epoch = 2.4

[contracts.flashloan-wrapper]
path = "contracts/borrow/production/mocks/flashloan-scripts/flashloan-wrapper.clar"
clarity_version = 3
epoch = 3.0

# [contracts.rewards-deployment]
# path = "contracts/borrow/deployment_mainnet/upgrades/rewards/rewards-deployment-v2-1.clar"
# clarity_version = 3
# epoch = 3.0

[contracts.incentives-trait]
path = "contracts/borrow/production/traits/incentives.clar"
clarity_version = 3
epoch = 3.0

[contracts.incentives-trait-v2-0]
path = "contracts/borrow/production/traits/incentives.clar"
clarity_version = 3
epoch = 3.0

[contracts.incentives-trait-v2-1]
path = "contracts/borrow/production/traits/incentives.clar"
clarity_version = 3
epoch = 3.0

[contracts.ft-trait]
path = "contracts/borrow/production/traits/ft-trait.clar"
clarity_version = 2
epoch = 2.4

[contracts.ft-mint-trait]
path = "contracts/borrow/production/traits/ft-mint-trait.clar"
clarity_version = 2
epoch = 2.4

[contracts.redeemeable-trait]
path = "contracts/borrow/legacy/v0/traits/redeemeable-trait.clar"
clarity_version = 2
epoch = 2.4

[contracts.redeemeable-trait-v1-2]
path = "contracts/borrow/production/traits/redeemeable-trait-v1-2.clar"
clarity_version = 2
epoch = 2.4

[contracts.vault-trait]
path = "contracts/borrow/production/traits/vault-trait.clar"
clarity_version = 2
epoch = 2.4

[contracts.oracle-trait]
path = "contracts/borrow/production/traits/oracle-trait.clar"
clarity_version = 2
epoch = 2.4

[contracts.flash-loan-trait]
path = "contracts/borrow/production/traits/flash-loan-trait.clar"
clarity_version = 2
epoch = 2.4

[contracts.pool-reserve-data]
path = "contracts/borrow/production/reserve-data/pool-reserve-data.clar"
clarity_version = 2
epoch = 2.4

[contracts.pool-reserve-data-1]
path = "contracts/borrow/production/reserve-data/pool-reserve-data-1.clar"
clarity_version = 2
epoch = 2.4

[contracts.pool-reserve-data-2]
path = "contracts/borrow/production/reserve-data/pool-reserve-data-2.clar"
clarity_version = 3
epoch = 3.0

[contracts.pool-reserve-data-3]
path = "contracts/borrow/production/reserve-data/pool-reserve-data-3.clar"
clarity_version = 3
epoch = 3.0

[contracts.pool-reserve-data-4]
path = "contracts/borrow/production/reserve-data/pool-reserve-data-4.clar"
clarity_version = 3
epoch = 3.0

[contracts.rewards-data-1]
path = "contracts/borrow/production/reserve-data/rewards-data-1.clar"
clarity_version = 3
epoch = 3.0

[contracts.math]
path = "contracts/borrow/legacy/v0/math/math.clar"
clarity_version = 2
epoch = 2.4

[contracts.math-v1-2]
path = "contracts/borrow/legacy/v1-2/math/math.clar"
clarity_version = 2
epoch = 2.4

[contracts.math-v2-0]
path = "contracts/borrow/production/math/math.clar"
clarity_version = 3
epoch = 3.0

[contracts.hk-cursor-v2]
path = "contracts/borrow/production/mocks/oracle/pyth/hiro-kit/hk-cursor-v2.clar"
clarity_version = 3
epoch = 3.0

[contracts.hk-ecc-v1]
path = "contracts/borrow/production/mocks/oracle/pyth/hiro-kit/hk-ecc-v1.clar"
clarity_version = 3
epoch = 3.0

[contracts.hk-merkle-tree-keccak160-v1]
path = "contracts/borrow/production/mocks/oracle/pyth/hiro-kit/hk-merkle-tree-keccak160-v1.clar"
clarity_version = 3
epoch = 3.0

[contracts.wormhole-traits-v1]
path = "contracts/borrow/production/mocks/oracle/pyth/wormhole/wormhole-traits-v1.clar"
clarity_version = 3
epoch = 3.0

[contracts.wormhole-core-v3]
path = "contracts/borrow/production/mocks/oracle/pyth/wormhole/wormhole-core-v3.clar"
clarity_version = 3
epoch = 3.0

[contracts.pyth-traits-v1]
path = "contracts/borrow/production/mocks/oracle/pyth/pyth-traits-v1.clar"
clarity_version = 3
epoch = 3.0

[contracts.pyth-storage-v3]
path = "contracts/borrow/production/mocks/oracle/pyth/pyth-storage-v3.clar"
clarity_version = 3
epoch = 3.0

[contracts.pyth-pnau-decoder-v2]
path = "contracts/borrow/production/mocks/oracle/pyth/pyth-pnau-decoder-v2.clar"
clarity_version = 3
epoch = 3.0

[contracts.pyth-oracle-v3]
path = "contracts/borrow/production/mocks/oracle/pyth/pyth-oracle-v3.clar"
clarity_version = 3
epoch = 3.0

[contracts.pyth-governance-v2]
path = "contracts/borrow/production/mocks/oracle/pyth/pyth-governance-v2.clar"
clarity_version = 3
epoch = 3.0

[contracts.pyth-oracle]
path = "contracts/borrow/production/mocks/oracle/pyth-oracle.clar"
clarity_version = 3
epoch = 3.0

[contracts.proposal-trait]
path = "contracts/borrow/production/governance/proposal-trait.clar"
clarity_version = 3
epoch = 3.0

[contracts.zest-governance]
path = "contracts/borrow/production/governance/zest-governance.clar"
clarity_version = 3
epoch = 3.0

[repl]
costs_version = 1
parser_version = 2

[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
